#!/bin/bash

echo "============================================"
echo "🔑 GitHub Secrets Configuration Helper"
echo "============================================"
echo ""
echo "You need to add these secrets to your GitHub repository:"
echo "Go to: https://github.com/croko22/laravel_ecole/settings/secrets/actions"
echo ""

echo "1️⃣  AWS_ACCESS_KEY_ID"
echo "   Value: (your AWS access key ID)"
echo "   Current AWS user: $(aws sts get-caller-identity --query 'Arn' --output text 2>/dev/null || echo 'Not configured')"
echo ""

echo "2️⃣  AWS_SECRET_ACCESS_KEY"
echo "   Value: (your AWS secret access key)"
echo "   ⚠️  This is sensitive! Don't share it."
echo ""

echo "3️⃣  PULUMI_ACCESS_TOKEN"
echo "   Get it from: https://app.pulumi.com/account/tokens"
echo "   Or create a new token with: pulumi login"
echo ""

echo "============================================"
echo "📝 How to add secrets:"
echo "============================================"
echo "1. Go to your GitHub repo: https://github.com/croko22/laravel_ecole"
echo "2. Click 'Settings' → 'Secrets and variables' → 'Actions'"
echo "3. Click 'New repository secret'"
echo "4. Add each secret listed above"
echo ""

echo "============================================"
echo "🧪 Test the workflow:"
echo "============================================"
echo "After adding secrets, push to main:"
echo "  git add ."
echo "  git commit -m 'Setup CI/CD'"
echo "  git push origin main"
echo ""
echo "Or trigger manually:"
echo "  Go to: https://github.com/croko22/laravel_ecole/actions"
echo "  Select '🚀 Deploy Laravel App to AWS EKS'"
echo "  Click 'Run workflow'"
echo ""
