apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-application
  template:
    metadata:
      labels:
        app: web-application
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "80"
    spec:
      volumes:
        - name: logs
          emptyDir: {}
        - name: views
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: cache
          emptyDir: {}
        - name: sessions
          emptyDir: {}
      securityContext:
        fsGroup: 82
      initContainers:
        - name: database-migrations
          image: backend:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: application-config
            - secretRef:
                name: application-secret
          command:
            - "php"
          args:
            - "artisan"
            - "migrate"
            - "--force"
      containers:
        - name: nginx
          imagePullPolicy: Never
          image: frontend:latest
          resources:
            requests:
              cpu: "200m"
              # memory: 32M
            # limits:
            #   cpu: 500m
            #   memory: 50M
          ports:
            - containerPort: 80
        - name: fpm
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: application-config
            - secretRef:
                name: application-secret
          securityContext:
            runAsUser: 82
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: logs
              mountPath: /var/www/html/storage/logs
            - name: views
              mountPath: /var/www/html/storage/framework/views
            - name: tmp
              mountPath: /tmp
            - name: cache
              mountPath: /var/www/html/bootstrap/cache
            - name: sessions
              mountPath: /var/www/html/storage/framework/sessions
          resources:
            requests:
              cpu: "200m"
          image: backend:latest
          ports:
            - containerPort: 9000
