apiVersion: v1
kind: Secret
metadata:
  name: application-secret
type: Opaque
data:
  REDIS_PASSWORD: cmRzaGFyZFBhc3MxMjM=
  DB_PASSWORD: c3FsaGFyZFBhc3MxMjM=
  DB_USERNAME: YXBwdXNlcg==
  APP_KEY: YmFzZTY0OlJ1TlNvUU94OE5WZ0V0M1RJN2ZPSExvb3JSME9JRmhMZUxrck96dVllVTg9
